= Tigase XMPP Server 8.2.0 Release Notes
:author: Wojciech Kapcia

Welcome to Tigase XMPP Server 8.2.0! This is a feature release a number of fixes and updates. Here is the list of most important features and changes and below the list of all release notes from all included components

== Highlights

=== MIX support

Version 8.2.0 brings in MIX support. Tigase MIX component is a component extending Tigase PubSub Component and providing support for https://xmpp.org/extensions/xep-0369.html[XEP-0369: MIX] protocol extensions being part of https://xmpp.org/extensions/xep-0369.html#family[MIX specification family].

MIX stands for Mediated Information eXchange (MIX) and it's basics are defined in https://xmpp.org/extensions/xep-0369.html[XEP-0369: Mediated Information eXchange (MIX)]:

> "an XMPP protocol extension for the exchange of information among multiple users through a mediating service. The protocol can be used to provide human group communication and communication between non-human entities using channels, although with greater flexibility and extensibility than existing groupchat technologies such as Multi-User Chat (MUC). MIX uses Publish-Subscribe to provide flexible access and publication, and uses Message Archive Management (MAM) to provide storage and archiving."

MIX Works in cluster (with ACS-MIX component, requires licence) and with all database, including MongoDB

=== Improvements to s2s connection

Version 8.2.0 brings a lot of improvements related to s2s connectivity: support for TLS1.3, improved logic during authentication and stream negotiation solving connectivity issues with various deployments.

=== Better handling of certificates

It's now possible to store certificates in the database making it easier to manage them, especially in clustered environment.

== Other significant changes

* Improved performance: reduced memory usage and decrease startup time
* Add publishing executor with rate limiting in PubSub
* Bring MUC specification support up to date
* Improve handling of multiple user session using same nickname in MUC
* Fixes and improvements to MUC ad-hoc scripts
* Enable HTTP File Upload by default with additional, optional, AWS S3 compatible backend
* Improvements to Web Setup to make installation even more straightforward
* Allow exposing `.well-known` in the root context to facilitate https://xmpp.org/extensions/xep-0156.html[XEP-0156: Discovering Alternative XMPP Connection Methods]
* Add option to redirect requests from http to https internally by Tigase XMPP Server
* Added support for sending VoIP push notifications using PushKit
* Support for storing APNS certificates in repository instead of filesystem for easier cluster deployments
* Add priority detection for push notifications to avoid excessive pushes to devices
* Inclusion of APNS certificate validity task that notifies if it's about to expire
* Add support for urn:xmpp:mam:2
* Add support for https://xmpp.org/extensions/xep-0308.html[XEP-0308: Last Message Correction]
* Deprecation of `Element` based events in favour of Object based events
* Deprecate Deprecate PartitionedStrategy in ACS-PubSub

== Per-component changes

include::../../../target/documentation/tigase-server/documentation/admin/text/tigase-server-current.asciidoc[leveloffset=+2]
include::../../../target/documentation/tigase-mix/documentation/text/tigase-mix-current.asciidoc[leveloffset=+2]
include::../../../target/documentation/tigase-pubsub/documentation/text/tigase-pubsub-current.asciidoc[leveloffset=+2]
include::../../../target/documentation/tigase-muc/documentation/text/tigase-muc-current.asciidoc[leveloffset=+2]
include::../../../target/documentation/tigase-http-api/documentation/text/tigase-http-api-current.asciidoc[leveloffset=+2]
include::../../../target/documentation/tigase-push/documentation/text/tigase-push-current.asciidoc[leveloffset=+2]
include::../../../target/documentation/tigase-message-archiving/documentation/text/tigase-message-archiving-current.asciidoc[leveloffset=+2]
include::../../../target/documentation/tigase-acs/documentation/text/tigase-ACS-current.asciidoc[leveloffset=+2]


